# Generated by Django 5.1.1 on 2024-09-23 09:10

from django.db import migrations


def create_users(apps, schema_editor):
    """
        For convenince of whomever testing
    """
    User = apps.get_model("users", "User")

    User.objects.create(
        id="550e8400-e29b-41d4-a716-446655440010", username="john_doe"
    )
    User.objects.create(
        id="550e8400-e29b-41d4-a716-446655440011", username="adam_scott"
    )
    User.objects.create(
        id="550e8400-e29b-41d4-a716-446655440012", username="tom_cruis"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_users),
    ]
