# Generated by Django 5.1.1 on 2024-09-23 09:08

from django.db import migrations


def create_transaction_data(apps, schema_editor):
    """
        For convenince of whomever testing
    """
    Transaction = apps.get_model("transactions", "Transaction")
    TransactionParticipant = apps.get_model(
        "transactions", "TransactionParticipant"
    )

    # Create Transaction instance
    txn = Transaction.objects.create(external_id="txn_001", total_amount=9000)

    # Create TransactionParticipant instances
    TransactionParticipant.objects.create(
        transaction=txn,
        user_id="550e8400-e29b-41d4-a716-446655440010",
        role="RECEIVER",
        share=3,
        share_amount=3000,
    )
    TransactionParticipant.objects.create(
        transaction=txn,
        user_id="550e8400-e29b-41d4-a716-446655440011",
        role="RECEIVER",
        share=3,
        share_amount=3000,
    )
    TransactionParticipant.objects.create(
        transaction=txn,
        user_id="550e8400-e29b-41d4-a716-446655440012",
        role="RECEIVER",
        share=3,
        share_amount=3000,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
        ("users", "0002_auto_20240923_0910"),
    ]

    operations = [
        migrations.RunPython(create_transaction_data),
    ]
